sudo: true
os: trusty
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  global:
  - secure: Pd5RX9ibGFSn2u8nZXPxDZeR8cz7T4Blj6CqpmJw/O3VBEoTuRNcGPXDBaBPvpLYdqiZLGYeVgJOJneA9wKyYebUyp2+G5CZ3zajmESwN7RFbRDXBNJiDgBk2NKpZfUKV3VSmSOkDjFK0KoRmIsqJs1jfGSxePdFmwXczZaQ70PqhdKvp9Uq8oPMryCILMVFJISkd7OxQqmxu5Yu6Q/OZw16VOGH/ryNFTU9PkeeyTWEQvAzYo75rlriWWDTAi2W2QbFnJOyy4+cM6n//HkiMHfTl0YIDDm/nhbJo2wDPVL656/A6fCrz0TGx9LoB0uLOGapAqrtn3bp4pTxYHjJN5hlfQs87URmFrigPuB/CfwjdMMfBm+KDNhzjO0aP5SwxGRptBPXkKk604AiTcTjo2bHxjDHnYFfRIPK4pRcTz4NlNu8q3gfDcwekgmp64xdHvfCmuPrZ+vT+Qofnw/Q/FkaeIjKsz/eWUkgnQhXOO8ZyrGH0ZWDVEKtnpSfgSi6huZHYavcgfV6at5hSF9/Pv8VIJkBoQwf/IAx52bIU3A7hcrL5fSmxK4hDnJdiSNsa/IiELP2q8P2ud4FQdEKKvgDZQpqXO9vlpy3PsXfQtwhxxQurNksjjjQWZ38IALlvCrx4t2nowb+e7qltXMvO15oBIJ1c0hf5o1lgdrINn4=
before_install:
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait 4
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg --wait 10
- sfdx force:org:delete -u ciorg -p
